# Generated by Django 4.2 on 2023-05-01 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_column='first_name', max_length=16, verbose_name='first name')),
                ('middle_name', models.CharField(db_column='middle_name', max_length=16, verbose_name='middle name')),
                ('email', models.EmailField(db_column='email', max_length=30, unique=True, verbose_name='email adress')),
                ('login', models.CharField(db_column='login', max_length=12, unique=True, verbose_name='login')),
                ('password', models.CharField(db_column='password', max_length=32, verbose_name='password')),
                ('gender', models.CharField(db_column='gender', max_length=6, verbose_name='user gender')),
                ('age', models.CharField(db_column='age', max_length=20, verbose_name='user age')),
                ('to_be_informed', models.BooleanField(db_column='to_be_informed', verbose_name='to be informed')),
                ('registered_at', models.IntegerField(db_column='registered_at', verbose_name='registerd time in tymestamp format')),
            ],
        ),
    ]
