# Generated by Django 4.2 on 2023-05-03 11:51

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=16)),
                ('middle_name', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('login', models.CharField(max_length=12, unique=True)),
                ('password', models.CharField(max_length=16)),
                ('gender', models.CharField(choices=[('woman', 'Woman'), ('man', 'Man')], max_length=6)),
                ('age', models.CharField(choices=[('under_18', 'Under 18 years old'), ('over_18', 'Over 18 years old')],
                                         max_length=20)),
                ('to_be_informed', models.BooleanField(default=False)),
                ('reg_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
