# Generated by Django 4.2.1 on 2023-05-05 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_user_password'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='MyRegisteredUser',
        ),
    ]
